### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by seuros**
ping @mdeiters

### CODE REVIEW

**Comment by seuros** [comment]
@mdeiters could you activate Travis build in the repo ?

**Comment by mdeiters** [comment]
how do i do that @seuros

**Comment by mdeiters** [comment]
id rather see .gitigonre Profile.dev then deletion, what do you think?

**Comment by whatupdave** [comment]
Hey @seuros why are you renaming `application` assets to `coderwall`?

**Comment by mdeiters** [comment]
@seuros  want to merge this in, thoughts on @whatupdave question?

**Comment by seuros** [comment]
Sorry, i was away. 
I renamed it to match the project name. 
Also since i use the same port for multiple projects. When i leave `application`, the browser load the cached version instead of the current project.

btw, are we using turbolinks ?

**Comment by mdeiters** [comment]
We are using turbo links

What is the benefit of renaming the app?

**Comment by andela-oakinniranye** [comment]
I think it would make more sense if there were tests for the application before all these changes cum. fixes are merged

**Comment by mdeiters** [comment]
Unfortunately because of the divergence in the code since these changes were initially made I'm going to close this PR. I *really* like the minitest stuff but I want to keep the codebase more uniformed to typical rails projects so changes like renaming application files etc work against that goal.

**Pull request closed without merging**
